version: "3.1"
services:
  nginx:
    restart: always
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./:/var/www/html/
      # - ./videos/:/var/www/static/
      # - ./images/:/var/www/static/
